### ISSUE TITLE
For arduino compatibility, HIGH and LOW are same as 1 and 0

### ISSUE THREAD

**Issue by jieq** [chibitronics/ltc-webview-layer#21]
In Arduino, HIGH is the same as 1 and LOW is the same as 0.  So for example, both of the following statements if(button == 1)  or if(button == HIGH) should mean the same.  

Currently only if(button == HIGH) seems to work...

**Comment by xobs** [comment]
This issue was moved to chibitronics/ltc-compiler-layer#4

**Comment by xobs** [comment]
This is an issue in the compiler layer (and the OS as well), so I've moved the issue to the compiler.
